### ISSUE TITLE
Milestone needed for Logstash 1.5.0 beta1

### ISSUE THREAD

**Issue by vincentbernat** [logstash-plugins/logstash-input-relp#2]
Hi!

The milestone is required by Logstash 1.5.0 beta1. It has been removed in https://github.com/logstash-plugins/logstash-input-relp/commit/29a7e49e9ba2f19dccb74bbb05c502a087a63b4b. Without it, Logstash refuses to run:

```
The error reported is:
  relp must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones
```

**Comment by untergeek** [comment]
I apologize for the inconvenience.  Milestones are deprecated in the current master, and all plugins have had them removed by script.  If you need to use a plugin right now, you can simply add `milestone 1` after the `class` declaration and above the `:config` options.

When RC1 is released, this will no longer be an issue.

**Comment by vincentbernat** [comment]
OK. I can also install a previous version (like 0.1.1). Thanks!

**Comment by knalli** [comment]
Sorry for overtaking the issue.. but where is documented how I can install an older plugin or where I should add `milestone 1`? Not for custom plugins, but for plugins installed via `$app/bin/plugin`?

**Comment by stuart-warren** [comment]
@knalli you should find your plugins in ``$app/vendor/bundle/jruby/1.9/gems`` where ever you unpacked the zip.
You'll then need to manually modify the relevant plugin to add a milestone, or alternatively, just install an older version of the plugin
``$app/bin/plugin install --version "= 0.1.1" logstash-input-someplugin``

@untergeek is there a vague target release date of RC1?

**Comment by Reeebuuk** [comment]
@untergeek is there a vague target release date of RC1? +1

**Comment by knalli** [comment]
@Reeebuuk LS 1.5RC2 is already out https://www.elastic.co/downloads/logstash
